###
GET http://localhost:5000/activities HTTP/1.1

###
GET http://localhost:5000/activities/match/you HTTP/1.1

###
PATCH http://localhost:5000/activities/3 HTTP/1.1
Content-Type: application/json

{
    "activity": "Ar Franklin"
}

###
PUT http://localhost:5000/activities/1 HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "quote": "Drinking water is essential to a healthy lifestyle.",
    "author": "Stephen Curry",
    "activity": "Stand up and go drink 2 glasses of water."
}