###
GET http://localhost:5000/activities HTTP/1.1

###
GET http://localhost:5000/activities/match/water HTTP/1.1

###
POST http://localhost:5000/activities HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "quote": "Drinking water is essential to a healthy lifestyle.",
    "author": "Stephen Curry",
    "activity": "water"
}
